# Generated by Django 2.2.2 on 2019-06-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='estadogeo',
        ),
    ]
