# Generated by Django 2.2.2 on 2019-06-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0002_remove_user_estadogeo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='estadogeo',
            field=models.BooleanField(default=False),
        ),
    ]
